#!/usr/bin/env python3
"""What a run spent, counted where the calls are made.

A person is generated by eight steps, and until now a run reported only
whether each of them worked. What each one consumed was invisible, so the
question a maintainer actually asks before changing a prompt — is this the
step that dominates the run, or the one that rounds to nothing — had no
answer short of reading the provider's dashboard and guessing which line
belonged to which step.

The ledger here answers it in tokens. Every call site that talks to a model
reports its response, the ledger attributes it to whichever step is open, and
the run ends by printing a row per step. Tokens rather than money: the rates
for the configured models are not in this repository, and a table of invented
numbers would read as authoritative while being wrong.

Attribution comes from :func:`step`, a context manager the orchestrator wraps
around each pipeline step. A call made outside any step is still counted, under
``UNATTRIBUTED`` — a missing wrapper should show up as a visible row rather
than as a silently smaller total.

The ledger is process-global because the alternative is threading a recorder
through every generation function, most of which exist to be callable on their
own. It is therefore only meaningful for a single run in a single process,
which is what the pipeline is.

The steps that run their calls side by side (``utils/concurrency.py``) record
from several threads at once, so the record list is guarded by a lock. The
attribution is not: which step is open is decided by the orchestrator between
steps, on the main thread, and holds for every worker of that step. A
:func:`step` block belongs on the main thread for the same reason — opened
inside a worker it would attribute the other workers' calls too.
"""

from __future__ import annotations

import threading
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional

UNATTRIBUTED = "Unattributed"
"""Step name for calls made outside any :func:`step` block."""


@dataclass
class CallRecord:
    """One model call: where it came from and what it consumed."""

    step: str
    label: str
    model: str
    input_tokens: int = 0
    cached_input_tokens: int = 0
    cache_write_tokens: int = 0
    output_tokens: int = 0
    reasoning_tokens: int = 0
    images: int = 0

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass
class StepUsage:
    """Everything one pipeline step consumed."""

    step: str
    calls: int = 0
    input_tokens: int = 0
    cached_input_tokens: int = 0
    cache_write_tokens: int = 0
    output_tokens: int = 0
    reasoning_tokens: int = 0
    images: int = 0
    models: List[str] = field(default_factory=list)

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


_records: List[CallRecord] = []
_records_lock = threading.Lock()
_step_stack: List[str] = []
_base_step: str = UNATTRIBUTED


def reset() -> None:
    """Forget everything recorded so far.

    Only a test and a script that runs two pipelines in one process need this;
    a normal run records once and reports once.
    """
    global _base_step
    with _records_lock:
        _records.clear()
    _step_stack.clear()
    _base_step = UNATTRIBUTED


def begin_step(name: str) -> None:
    """Attribute everything from here on to ``name``.

    The orchestrator runs its steps one after another and lets each one fail
    on its own, so there is no block that a step both begins and ends inside —
    wrapping eight ``try`` bodies in a context manager would say the same
    thing at eight times the indentation. A step simply announces itself, and
    the announcement holds until the next one.
    """
    global _base_step
    _base_step = name


def current_step() -> str:
    """The step calls are attributed to right now."""
    return _step_stack[-1] if _step_stack else _base_step


@contextmanager
def step(name: str) -> Iterator[None]:
    """Attribute every call made inside the block to ``name``.

    Nests, so a step that delegates to a sub-phase can open its own block
    without losing the outer attribution when it closes.
    """
    _step_stack.append(name)
    try:
        yield
    finally:
        _step_stack.pop()


def _count(container: Any, *names: str) -> int:
    """Read the first of ``names`` that is present, as an int.

    The usage payload is a model object for the text API and, for some image
    models, absent entirely. Field names also differ between the two — text
    calls report ``input_tokens``, older shapes ``prompt_tokens`` — so each
    figure is looked up by every name it goes by and defaults to zero.
    """
    if container is None:
        return 0
    for name in names:
        value = getattr(container, name, None)
        if value is None and isinstance(container, dict):
            value = container.get(name)
        if isinstance(value, (int, float)):
            return int(value)
    return 0


def record_response(
    model: str,
    response: Any,
    *,
    label: str = "",
    images: int = 0,
    step_name: Optional[str] = None,
) -> CallRecord:
    """Record what ``response`` reports it consumed.

    A response with no usage payload — an image model that does not report
    one, a stub in a test — still produces a record, so the call is counted
    even where its tokens cannot be. ``images`` counts pictures returned,
    which is the only unit some image calls are billed in.
    """
    usage = getattr(response, "usage", None)
    if usage is None and isinstance(response, dict):
        usage = response.get("usage")
    input_details = getattr(usage, "input_tokens_details", None)
    if input_details is None and isinstance(usage, dict):
        input_details = usage.get("input_tokens_details")
    output_details = getattr(usage, "output_tokens_details", None)
    if output_details is None and isinstance(usage, dict):
        output_details = usage.get("output_tokens_details")

    record = CallRecord(
        step=step_name or current_step(),
        label=label,
        model=model,
        input_tokens=_count(usage, "input_tokens", "prompt_tokens"),
        cached_input_tokens=_count(input_details, "cached_tokens"),
        cache_write_tokens=_count(input_details, "cache_write_tokens"),
        output_tokens=_count(usage, "output_tokens", "completion_tokens"),
        reasoning_tokens=_count(output_details, "reasoning_tokens"),
        images=images,
    )
    with _records_lock:
        _records.append(record)
    return record


def records() -> List[CallRecord]:
    """Every call recorded so far, in the order it was made."""
    with _records_lock:
        return list(_records)


def by_step() -> List[StepUsage]:
    """One row per step, in the order the steps first spent anything."""
    rows: Dict[str, StepUsage] = {}
    for record in records():
        row = rows.setdefault(record.step, StepUsage(step=record.step))
        row.calls += 1
        row.input_tokens += record.input_tokens
        row.cached_input_tokens += record.cached_input_tokens
        row.cache_write_tokens += record.cache_write_tokens
        row.output_tokens += record.output_tokens
        row.reasoning_tokens += record.reasoning_tokens
        row.images += record.images
        if record.model and record.model not in row.models:
            row.models.append(record.model)
    return list(rows.values())


def totals() -> StepUsage:
    """Every step added together, under the name ``Total``."""
    total = StepUsage(step="Total")
    for row in by_step():
        total.calls += row.calls
        total.input_tokens += row.input_tokens
        total.cached_input_tokens += row.cached_input_tokens
        total.cache_write_tokens += row.cache_write_tokens
        total.output_tokens += row.output_tokens
        total.reasoning_tokens += row.reasoning_tokens
        total.images += row.images
        for model in row.models:
            if model not in total.models:
                total.models.append(model)
    return total


def as_dict() -> Dict[str, Any]:
    """The ledger as plain data, for writing to a file."""

    def row_dict(row: StepUsage) -> Dict[str, Any]:
        return {
            "step": row.step,
            "calls": row.calls,
            "input_tokens": row.input_tokens,
            "cached_input_tokens": row.cached_input_tokens,
            "cache_write_tokens": row.cache_write_tokens,
            "output_tokens": row.output_tokens,
            "reasoning_tokens": row.reasoning_tokens,
            "images": row.images,
            "total_tokens": row.total_tokens,
            "models": row.models,
        }

    return {
        "steps": [row_dict(row) for row in by_step()],
        "total": row_dict(totals()),
        "calls": [
            {
                "step": record.step,
                "label": record.label,
                "model": record.model,
                "input_tokens": record.input_tokens,
                "cached_input_tokens": record.cached_input_tokens,
                "cache_write_tokens": record.cache_write_tokens,
                "output_tokens": record.output_tokens,
                "reasoning_tokens": record.reasoning_tokens,
                "images": record.images,
            }
            for record in records()
        ],
    }


def _thousands(value: int) -> str:
    return f"{value:,}"


def format_report() -> str:
    """The per-step table, as the run prints it."""
    rows = by_step()
    if not rows:
        return "No model calls were recorded."

    header = (
        "Step",
        "Calls",
        "Input",
        "Cached",
        "Written",
        "Output",
        "Reasoning",
        "Images",
    )
    body = [
        (
            row.step,
            _thousands(row.calls),
            _thousands(row.input_tokens),
            _thousands(row.cached_input_tokens),
            _thousands(row.cache_write_tokens),
            _thousands(row.output_tokens),
            _thousands(row.reasoning_tokens),
            _thousands(row.images),
        )
        for row in rows + [totals()]
    ]
    widths = [
        max(len(header[column]), *(len(line[column]) for line in body))
        for column in range(len(header))
    ]

    def line(cells: Any) -> str:
        first = str(cells[0]).ljust(widths[0])
        rest = " ".join(
            str(cell).rjust(widths[column + 1]) for column, cell in enumerate(cells[1:])
        )
        return f"{first}  {rest}"

    separator = "-" * (widths[0] + 2 + sum(widths[1:]) + len(widths) - 2)
    printed = [line(header), separator]
    printed += [line(cells) for cells in body[:-1]]
    printed += [separator, line(body[-1])]
    return "\n".join(printed)


def print_report(title: str = "AI USAGE BY STEP") -> None:
    """Print the per-step table under a banner, if anything was recorded."""
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)
    print(format_report())
    print(
        "\nTokens only: the rates for these models are not configured in this "
        "repository, so no monetary total is claimed."
    )
