#!/usr/bin/env python3
"""Emit the standalone HTML page.

Everything is inlined — CSS, JS and the payload — so the file works from
`file://`, from a repo checkout, or attached to an email, with no build step
and no network access.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

ASSETS = Path(__file__).resolve().parent / "assets"

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Life Data Stories — story generation pipeline</title>
<meta name="description" content="Interactive documentation of the personal and meta story generation pipelines: steps, prompts, schemas and recorded runs.">
<style>
__CSS__
</style>
</head>
<body>
<div class="wrap">
  <header class="page">
    <h1>Story generation pipeline</h1>
    <p class="lede">
      Every step that turns encyclopedia articles into a Life Data Story. The
      two pipelines are documented separately — pick one below. Facts on this
      page are extracted from <code>scripts/</code> at build time, so they
      cannot drift from the code; timings and real prompts come from recorded
      runs.
    </p>
    <div class="meta-row" id="meta-row"></div>
    <div class="tiles" id="tiles"></div>
  </header>

  <!-- One panel is rendered at a time; every section below belongs to the
       selected pipeline and is redrawn when the tab changes. -->
  <nav class="pipeline-tabs" id="pipeline-tabs" role="tablist" aria-label="Pipeline"></nav>
  <p class="panel-lede" id="panel-lede"></p>

  <!-- The toolbar sticks only within this section, so it stops following the
       reader once the chart has scrolled past. -->
  <section class="chart-section" id="panel" role="tabpanel">
    <div class="toolbar">
      <input class="search" id="search" type="search" placeholder="Search steps, prompts, schemas…" aria-label="Search the pipeline">
      <div class="filters" id="filters"></div>
    </div>
    <p class="hint" id="hint"></p>

    <figure class="figure">
      <div class="chart-scroll">
        <svg id="flow" role="img" aria-label="Flow chart of the story generation pipeline"></svg>
      </div>
      <figcaption id="flow-caption"></figcaption>
    </figure>
  </section>

  <section class="runs">
    <h2>Recorded runs</h2>
    <div id="runs"></div>
  </section>

  <section class="appendix">
    <h2 style="margin-top:46px">Entry point</h2>
    <p class="section-lede">Command-line options, read from the script's argument parser.</p>
    <div id="appendix"></div>
  </section>

  <footer class="page">
    Generated by <code>scripts/generate_pipeline_docs.py</code>. Step
    explanations are written by a language model from the source and cached
    against it; every other fact is parsed directly from the scripts.
  </footer>
</div>

<aside class="drawer" id="drawer" aria-label="Step details">
  <div class="drawer-head">
    <h2 id="drawer-title">Step</h2>
    <button class="drawer-close" id="drawer-close" type="button" aria-label="Close details">&times;</button>
  </div>
  <div class="drawer-body" id="drawer-body"></div>
</aside>

<script id="payload" type="application/json">__DATA__</script>
<script>
window.PIPELINE = JSON.parse(document.getElementById("payload").textContent);
</script>
<script>
__JS__
</script>
</body>
</html>
"""


def render(payload: Dict[str, Any]) -> str:
    css = (ASSETS / "style.css").read_text(encoding="utf-8")
    script = (ASSETS / "app.js").read_text(encoding="utf-8")
    # `</script>` inside the payload would close the tag early; escaping the
    # slash keeps the JSON valid while making that impossible.
    data = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    return (
        TEMPLATE.replace("__CSS__", css)
        .replace("__JS__", script)
        .replace("__DATA__", data)
    )


def write(payload: Dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(payload), encoding="utf-8")
    return path
